"""Automatic memory extraction from conversations.

Runs asynchronously after a conversation ends to extract valuable
episodic memories (task experiences, facts, preferences, feedback).
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from loguru import logger

from comobot.agent.episodic.models import EpisodicMemory
from comobot.agent.episodic.store import EpisodicMemoryStore

if TYPE_CHECKING:
    from comobot.agent.memory_search import MemorySearchEngine
    from comobot.providers.base import LLMProvider

EXTRACTION_PROMPT = """\
Analyze the following conversation and extract valuable memories. Only extract the following types:

1. **task**: What task was completed, what method was used, what was the result
   - Example: "User asked to implement JWT auth using PyJWT, key point was setting the algorithm parameter explicitly"
2. **fact**: Factual information about the user, project, or environment
   - Example: "User's project uses PostgreSQL 14, deployed on AWS ap-northeast-1"
3. **preference**: User preferences and habits
   - Example: "User prefers functional programming style, dislikes OOP"
4. **feedback**: User feedback on agent behavior
   - Example: "User said 'don't add type annotations every time', should reduce unnecessary type annotations"

Rules:
- Only extract information that would be helpful in future conversations
- Do NOT extract temporary or one-off information
- Each memory should be self-contained and understandable without context
- Confidence reflects certainty (user explicitly stated = 1.0, inferred = 0.5-0.8)
- If there is nothing worth extracting, return an empty list

Output format (JSON only, no other text):
{
  "memories": [
    {
      "type": "fact",
      "content": "Memory content",
      "confidence": 0.9,
      "tags": ["python", "authentication"]
    }
  ]
}
"""


class MemoryExtractor:
    """Extract episodic memories from a conversation using LLM analysis."""

    def __init__(
        self,
        store: EpisodicMemoryStore,
        provider: LLMProvider,
        model: str | None = None,
        memory_engine: MemorySearchEngine | None = None,
        confidence_threshold: float = 0.6,
    ):
        self._store = store
        self._provider = provider
        self._model = model
        self._memory_engine = memory_engine
        self._confidence_threshold = confidence_threshold

    async def extract(
        self,
        messages: list[dict],
        source_session: str = "",
        source_channel: str = "",
    ) -> list[EpisodicMemory]:
        """Extract memories from a conversation (async, non-blocking).

        Should be called via asyncio.create_task() to avoid blocking responses.
        """
        # Build conversation text for the LLM
        conversation = self._format_conversation(messages)
        if not conversation.strip():
            return []

        try:
            response = await self._provider.chat(
                messages=[
                    {"role": "system", "content": EXTRACTION_PROMPT},
                    {"role": "user", "content": conversation},
                ],
                model=self._model,
                temperature=0.1,
                max_tokens=2048,
            )
        except Exception:
            logger.debug("Memory extraction LLM call failed for {}", source_session)
            return []

        # Parse JSON from response
        raw_memories = self._parse_response(response.content)
        if not raw_memories:
            return []

        # Filter by confidence threshold and deduplicate
        created: list[EpisodicMemory] = []
        for raw in raw_memories:
            confidence = raw.get("confidence", 0.5)
            if confidence < self._confidence_threshold:
                continue

            # Deduplication: check semantic similarity with existing memories
            if await self._is_duplicate(raw.get("content", "")):
                logger.debug("Skipping duplicate memory: {}", raw["content"][:60])
                continue

            memory = EpisodicMemory(
                id="",  # Will be generated by store
                type=raw.get("type", "fact"),
                content=raw.get("content", ""),
                confidence=confidence,
                source_session=source_session,
                source_channel=source_channel,
                tags=raw.get("tags", []),
            )
            try:
                memory = await self._store.create(memory)
                created.append(memory)
            except Exception:
                logger.debug("Failed to store episodic memory: {}", memory.content[:60])

        if created:
            logger.info("Extracted {} episodic memories from {}", len(created), source_session)
        return created

    @staticmethod
    def _format_conversation(messages: list[dict]) -> str:
        """Format messages into readable conversation text for the LLM."""
        lines: list[str] = []
        for m in messages:
            role = m.get("role", "unknown")
            if role == "process":
                continue  # Skip process messages
            content = m.get("content", "")
            if isinstance(content, list):
                # Multimodal: extract text parts
                content = " ".join(c.get("text", "") for c in content if c.get("type") == "text")
            if not content:
                continue
            # Truncate very long messages
            if len(content) > 1000:
                content = content[:1000] + "..."
            lines.append(f"{role}: {content}")
        return "\n".join(lines)

    @staticmethod
    def _parse_response(content: str | None) -> list[dict]:
        """Parse the LLM extraction response as JSON."""
        if not content:
            return []
        # Try to find JSON in the response
        try:
            # First try direct parse
            data = json.loads(content)
            return data.get("memories", [])
        except json.JSONDecodeError:
            pass
        # Try to extract JSON block from markdown
        import re

        match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", content, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group(1))
                return data.get("memories", [])
            except json.JSONDecodeError:
                pass
        # Try to find a JSON object anywhere
        match = re.search(r"\{[^{}]*\"memories\"[^{}]*\[.*?\]\s*\}", content, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group(0))
                return data.get("memories", [])
            except json.JSONDecodeError:
                pass
        logger.debug("Failed to parse memory extraction response")
        return []

    async def _is_duplicate(self, content: str) -> bool:
        """Check if a memory with similar content already exists (semantic dedup)."""
        if not self._memory_engine or not content:
            return False
        try:
            chunks = self._memory_engine.search(content, max_results=3, file_filter="episodic/")
            # Consider duplicate if similarity score > 0.85
            for chunk in chunks:
                if chunk.score >= 0.85:
                    return True
        except Exception:
            pass
        return False
