import type { GlobalThemeOverrides } from 'naive-ui'

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#FAFAFA',
    primaryColorHover: '#E4E4E7',
    primaryColorPressed: '#A1A1AA',
    primaryColorSuppl: '#FAFAFA',
    bodyColor: '#09090B',
    cardColor: '#111115',
    modalColor: '#111115',
    popoverColor: '#1C1C22',
    tableColor: '#111115',
    tableColorHover: '#1C1C22',
    inputColor: '#1C1C22',
    inputColorDisabled: '#141418',
    textColorBase: '#FAFAFA',
    textColor1: '#FAFAFA',
    textColor2: '#A1A1AA',
    textColor3: '#52525B',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: '10px',
    borderRadiusSmall: '6px',
    fontFamily: '"Inter", "PingFang SC", -apple-system, sans-serif',
    fontFamilyMono: '"JetBrains Mono", "Fira Code", monospace',
  },
  Button: {
    colorPrimary: '#FAFAFA',
    colorHoverPrimary: '#E4E4E7',
    textColorPrimary: '#09090B',
    borderRadiusMedium: '8px',
  },
  Menu: {
    itemColorActive: 'rgba(255,255,255,0.06)',
    itemColorHover: 'rgba(255,255,255,0.04)',
    itemTextColorActive: '#FAFAFA',
    itemIconColorActive: '#FAFAFA',
    borderRadius: '8px',
  },
  Layout: {
    siderColor: '#0D0D10',
    headerColor: '#0D0D10',
  },
}

export const lightThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#0A0A0A',
    primaryColorHover: '#3F3F46',
    primaryColorPressed: '#18181B',
    primaryColorSuppl: '#0A0A0A',
    bodyColor: '#FFFFFF',
    cardColor: '#FFFFFF',
    modalColor: '#FFFFFF',
    popoverColor: '#FFFFFF',
    tableColor: '#FFFFFF',
    tableColorHover: '#F8F8F8',
    inputColor: '#F4F4F5',
    inputColorDisabled: '#F0F0F0',
    textColorBase: '#0A0A0A',
    textColor1: '#0A0A0A',
    textColor2: '#6B6B6B',
    textColor3: '#A0A0A0',
    borderColor: '#E8E8E8',
    borderRadius: '10px',
    borderRadiusSmall: '6px',
    fontFamily: '"Inter", "PingFang SC", -apple-system, sans-serif',
    fontFamilyMono: '"JetBrains Mono", "Fira Code", monospace',
  },
  Button: {
    colorPrimary: '#0A0A0A',
    colorHoverPrimary: '#3F3F46',
    textColorPrimary: '#FFFFFF',
    borderRadiusMedium: '8px',
  },
  Menu: {
    itemColorActive: 'rgba(0,0,0,0.06)',
    itemColorHover: 'rgba(0,0,0,0.04)',
    itemTextColorActive: '#0A0A0A',
    itemIconColorActive: '#0A0A0A',
    borderRadius: '8px',
  },
  Layout: {
    siderColor: '#F8F8F8',
    headerColor: '#F8F8F8',
  },
}
